api_origin="http://example.com"
id="1"
# delta_volume=0
# led_server_origin="http://127.0.0.1:8080"
# mic_name="BY Y02"
# speaker_name="BY Y02"
# main_button_pin=18
# sub_button_pin=24
# delta_volume=0
# skip_introduction=false
